# Map file path patterns to labels used by the actions/labeler action
examples/*: example
examples/**: example
docs/**: documentation
docs/*: documentation
questions/**: question
answers/**: answer
.github/**: chore
*.md: documentation
